import uuid

from aplication.users.user import User
from aplication.users.user_interface import userRepositoryInterface


class UserRepository(userRepositoryInterface):
    async def get_user(id: uuid): ...

    async def list_users(): ...

    async def create_user(user: User): ...

    async def edit_user(user: User): ...

    async def create_or_update(self, user: User): ...

    async def delete_user(id: uuid): ...
